language: node_js
node_js:
- "node"
deploy:
  provider: heroku
  api_key:
    secure: bIKlvxeZ+W5377ObFfXNp972a70GQDEswZ3yie34e8J+PqhqTacgWEadHpdfjoB0ahrZyEiF34moLD11WJV52WrbILVBwxastEW7MgopROqSElsGyFutDqfzLZmvGQnwz+FFWwjkC2P/0pZQ6kQ6HPS2hgex+qBfEeclwxIL6VhX5yoPR5Ssmbl0O8uMN7yxD4EvBAx0OgyBORC/YDiKP/OkIgEhA4ksS0j3st83papCXSu3xxoVllfhn8BncwvLBg2cBr3YFhT/kTdhEGt6d8gs8ypyqhZ1jQKacRF4IlnAxNLc8REaTkzFyWYnNNG1jT1Ai9eyxzGaOjbiSFHToAnr98Bh/UkbgmPcb3sDvb/9ZJE1lGAV0mynluobBhbQuJlOAjnCsJTSxs8alzsVvG4uooQ7Ndi/I8NGHrfW0/GOTxVg9Ocy7gwoPZjIRm7Ll4fVOHGKm1MFOKn/6kRgm9MwC/KOzx/eTnHBTrLGA19NBcRWcsSMLMBP14ixZSx5nhc3Qw7bgDHvWeVwHwaS1bbdal8XQQOCQ9mjzuZAuN6tteH/0nhjprbkOM8MNvgQBqn0mODERTlcuPwz89feCtvPL25Iq7mi1+SBiDT/UdrUOEFwQMzXEoEmC9SFH8cgPv7VN0NJegWtmRBKD8OX1C1XblcX2lEWtoRMSPh7lz0=
  app: star-wars-spa
  on:
    repo: Scorpio750/star-wars-spa
