language: node_js
node_js:
- node
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: KSY1csYUMW/lCfCE0gc8OXKyE6MH65KFRZoK6VCBYzBP7GjFtFlC63AyLNLsr62TM1JSfULbYWcLKyY277Mq5RmnuN0GurgEcRv5agJp6x3cLKToBE9C6CdOMHJBXfWv+LFFQ+LiEvQLR18cjgd0hOwSiuP1NtllxpZf7mCgKoKegkCqjoGqJDc6+atjJztDIZTdRmcy+m4hzmJnZRssdKxffD/OnsUqJrOkGhr/hLjjsZ4RnK7aZxtbIVXRxPR3OQATZ8iLuSDHIyw6aZTXPhgqMa3u1rFaCCCrAMcY4HYJq3dUOZLbZuQ/6OcqeGpU9U1n/C1rhphhM2N6ISEsECIyA6HEoQcMdfyvJRoNI5S0magLgrnVPeSCib2nZBRAXNo5MHYr4qS8pi/kwEYAHsQsfLf+Q9QqyWEvmdqhlrrfl0JkVShTyKvIsBqGcQz8xeKVeXWag/MUYGiW6OVeww+3MxC3EDfAN5mOqWgxQPJDbuHZYIfEvHFaz9Vx3QY18E98RUfw3Bsz+bhyzBTxdFdZVxXHrF8yLhx8ONPj30x0M2tTEHHu70A8mZY9YFikSTe7jwcamps/dNGXDOuBtDONIYyoP7wZaiUMkIIUEuIy7CQaPxnhZa7P00QuU7o1sZqRPiaiDUobXD/YfAbUQ5fWgKisagYs0b78kGaz+qs=
  app: star-wars-spa
  on:
    repo: Scorpio750/star-wars-spa
