language: node_js
node_js:
- node
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: nCU7PsawZ0F+JLzTpF2eh7A+ZuZvT4XsCZP+nyfSk70HE7NKLBAOaENfOtyfi3rUD2ENGbln+d/VbwQrKnGQTf6UFSXxif0Ac+cGhHRrCIX6cyhfrE4Cvn8/G6t5Fe4Q9rNUNDYPfLOCzAZUUNkbTxgIJuVVt6HAtqW965hurslHgNAXo9AK7y67pSuDiU+J6/0Pq2xlIQQhgCiI/SfKhe/K/+Hed+f5rQxcBqRx8KtCzwuqhGYXw+TAGUnxkfAOQFSCCmT1afRmqZi0AQaboxELXMpRtLyzhGPVQP1SKd0UNnAazmGod33gbUKES3UsLUgOne1VZ6cap8UMIvwcd1qdKwWzvQ7A1HbPGemEDmgEDoGAleq5u5INuiw6GSZKILvnl3bcNFM9kTyYQQBtrhhYcPtCbzGzIXTkf4/2LzJMoMyTpqQcTnRCki9u9ALtGP3HCWJLAKVNY8cee4GlqIKNxO6TSwHQkOUGpUsDxxOJ761AB6lLqdKD99AknmI5VQNqjk9UjqYeXfugmA3hWBYf+RP8iXJIYkdZWic9Cmcm6UDfC2OP1wG8EbTtprRILzJW/Qxyau0ukqBLWR4AelE2XbHVgPR1Dpb8MJrRE3DooiBi0VvjXLrPtcsovSsFpHQ1cFtrtj6nJZTN1lgHjn94Wt0P+IYGghR+jYsjT3o=
  app: star-wars-spa
  on:
    repo: Scorpio750/star-wars-spa
