language: node_js
node_js:
- node
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: CoFjgTmVX65nM9c4A9NxelAHy55++HHbhFwZ0+kzGzTSs7pHW4GyCxe796l8SyEzCJf/n1aGB9zV9krEIfjNfy5kPSm9MPiwlNGUVdBlzLy9Y73543jaQ26gnc4fRkL2TpMRwRZUvV2KWurVlVb8GkUjdhaCTuV7N2p1rFUWCxqkwezr47PuHKHyEiDEbCAo70LJoL4QlI5HpAjsdExhI/tnvLHI3P4i/5aL3tChk1M/KA97A3Gt1sHBIzyS/syzdN7cpdZR7pvBFk384wYQGxNOfwQIWWbYMVJcN/dq4+QOk61w6Ju8iRP6hC8MtRZYsBHKFP+zn5odO6A4WvvFRIqwu82YXsPFHhBkiLAPgVujFBwyxkXyomg1gw73+tuj6jhK2svhBRVwcvKqb5HMFSMImADbU/kPeRTjb3jGBnMrGdHXx+JOYlbUHhQbUaSE+dvFJNG3aon4j3P6Hx+UNkoso0jfF+I55iRvXCwG78H9PtVjWZ04N8W86srhUj4iKr9r2kcwkShNKsYz/dmdZ0TeND51oTVfI8LvFIzr781jEWWUX4WZ4wYeIzJEZmzJXAGj5Q+TsXjEYeXdGsQGHSokSySiZouHiCTL8NFnXu34gwU1PePhpbB+UqoA/o/5Wtqc21f+9fVNQxMm0bvaJbelgRgHVAAB8w3UVyuoNcs=
  app: star-wars-spa
  on:
    repo: Scorpio750/star-wars-spa
